### ISSUE TITLE
Deprecated selector in `php-integrator-annotations/styles/main.less`

### ISSUE THREAD

**Issue by hultberg** [php-integrator/atom-annotations#11]
More heads up for 1.13.0:

In `php-integrator-annotations/styles/main.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
- `atom-text-editor .gutter .line-number.override .icon-right,
  atom-text-editor::shadow .gutter .line-number.override .icon-right` => `atom-text-editor .gutter .line-number.override .icon-right,
  atom-text-editor .gutter .line-number.syntax--override .icon-right`
- `atom-text-editor .gutter .line-number.override .icon-right:before,
  atom-text-editor::shadow .gutter .line-number.override .icon-right:before` => `atom-text-editor .gutter .line-number.override .icon-right:before,
  atom-text-editor .gutter .line-number.syntax--override .icon-right:before`
- `atom-text-editor .gutter .line-number.abstract-override .icon-right,
  atom-text-editor::shadow .gutter .line-number.abstract-override .icon-right` => `atom-text-editor .gutter .line-number.abstract-override .icon-right,
  atom-text-editor .gutter .line-number.abstract-override .icon-right`
- `atom-text-editor .gutter .line-number.abstract-override .icon-right:before,
  atom-text-editor::shadow .gutter .line-number.abstract-override .icon-right:before` => `atom-text-editor .gutter .line-number.abstract-override .icon-right:before,
  atom-text-editor .gutter .line-number.abstract-override .icon-right:before`
- `atom-text-editor .gutter .line-number.implementation .icon-right,
  atom-text-editor::shadow .gutter .line-number.implementation .icon-right` => `atom-text-editor .gutter .line-number.implementation .icon-right,
  atom-text-editor .gutter .line-number.syntax--implementation .icon-right`
- `atom-text-editor .gutter .line-number.implementation .icon-right:before,
  atom-text-editor::shadow .gutter .line-number.implementation .icon-right:before` => `atom-text-editor .gutter .line-number.implementation .icon-right:before,
  atom-text-editor .gutter .line-number.syntax--implementation .icon-right:before`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by Gert-dev** [comment]
Thanks for the heads up. Out of curiosity: are you getting these deprecation warnings in Atom 1.11 or 1.12? (My distro hasn't updated to 1.11 yet.) Marking as bug as it should be fixed ASAP.

**Comment by hultberg** [comment]
@Gert-dev I'm using Atom 1.13 (build on master branch)
