### ISSUE TITLE
Multiple implementations are ignored

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-annotations#12]
With core and base version 1.3, the method `implementation` property is an array as a single method can implement multiple interface methods. We should show this information in the tooltip and allow the user to select the implemented method to navigate to in a menu.

[1] would be useful here.

[1] https://github.com/steelbrain/intentions/issues/15

**Comment by Gert-dev** [comment]
Closing this for now, as it is a very rare case and it requires support in the core, first.
