### ISSUE TITLE
Don't show annotation while inside callback function

### ISSUE THREAD

**Issue by MCStreetguy** [php-integrator/atom-annotations#15]
While writing callback functions, the package shows up the annotation for the callback function.
In my case this overlays nearly the whole code of the function i've written before as you can see in the following screenshot:

![screenshot](https://user-images.githubusercontent.com/8970747/34457793-83b128c8-edbc-11e7-8eb8-71abba1f2dac.png)

Is it possible to limit this annotation to the head of the function instead of showing it within the whole function?

**Comment by Gert-dev** [comment]
Actually, these are signature help popups (call tips), not annotations. Annotations are the little markers in the gutter that identify method or property overloads and interface method implementations.

In any case, [this was already reported as an issue in the core](https://gitlab.com/php-integrator/core/issues/150). I'll follow it up there, but thanks for reporting it anyways!
