### ISSUE TITLE
Add annotations on interface methods with their implementations.

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-annotations#5]
We could add annotations to interface methods in interfaces themselves, allowing the user to navigate to the definition of the method in classes that implement the method. This involves using the `directImplementors` property of the class information to analyze classes that directly use the interface, as well as any subclasses (recursively) of those classes.

Note that the following applies:
- Classes must implement the methods of an interface themselves, unless they are abstract.
- Interfaces can also extend other interfaces, so the children of an interface must also be checked.

Care should be taken that this does not hurt performance (especially the recursing). Perhaps the recursing itself can be delayed until the intention is clicked and `directInterfaces` can be used as an indication if the annotation should be shown.

We could use something like the intentions package [1] to show a list of matches if there is more than one, allowing the user to click the one he wants to navigate to. An alternative would be to show a view, much like the "Find in project" in Atom itself. This view could show a spinner while matching is occurring.

[1] https://atom.io/packages/intentions
##

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/390).
