### ISSUE TITLE
Show an annotation for classlikes that allows navigating to related classlikes.

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-annotations#7]
We could show an annotation in the gutter for interfaces, classes and traits that shows a menu of all related classes, such as:
- Classes that extend this class.
- Interfaces that extend this interface.
- Classes that implement this interface.
- Classes that use this trait.

Clicking one of the related classes will take you to its definition.
##

**Comment by Gert-dev** [comment]
Closing this as this package will be merged into the [base](https://github.com/php-integrator/atom-base/) package. [This issue has been reposted there](https://github.com/php-integrator/atom-base/issues/389).
